[project]
name = "a-boolean-affair"
authors = [
    {name = "Lisa Chen", email = "lisa.hl.chen@gmail.com"}
]
version = "0.1.0"
description = "Add your description here" # TODO fill out description
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

